name       : numix-icon-theme
version    : 21.10.31
release    : 20
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/refs/tags/21.10.31.tar.gz : a5a703259b3242ec4fe77eb20b70fb4b4f0bf9c61d9550043c770dd563e62556
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly coloured background for applications and simplistic devices, toolbars and status icons.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix,Numix-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
