name       : numix-icon-theme
version    : 201610060518
release    : 12
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme/numix-icon-theme_0.3+871~201610060518~ubuntu16.10.1.tar.xz : aa4f0e81f0f70101a2e8e65930d3317f269906cee52303976f30f6426b576b36
license    : GPL-3.0
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
