name       : numix-icon-theme
version    : 22.08.16
release    : 21
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/refs/tags/22.08.16.tar.gz : 4014200c5ee0c35ce0f31bfd52ccc0bc4fe6857b0adb38a9dc8ef2d65fe72e01
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly coloured background for applications and simplistic devices, toolbars and status icons.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix,Numix-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
