name        : numix-icon-theme
version     : 20150607
release     : 9
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme/numix-icon-theme_0.3+412~201506070201~ubuntu15.04.1.tar.xz : f81c5b389dd883d974aae4adb4f481c0931e0d0d58eed512819d9ff88ae0217a
license     : GPL-3.0+
summary     : The Numix Icon Theme
description : |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
