name       : numix-icon-theme
version    : 19.09.20
release    : 16
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/19.09.20.tar.gz : 39010537d0f8ea358da5c7d50a14554b7755ffa445c8b6a392f3243662279c9a
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly coloured background for applications and simplistic devices, toolbars and status icons.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix,Numix-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
