name       : numix-icon-theme
version    : 23.04.26
release    : 25
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/refs/tags/23.04.26.tar.gz : 0cbc4b49127b177c9f43a4e78462032ed09a4efdc82dcbad83f131c7d6e73b2a
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly coloured background for applications and simplistic devices, toolbars and status icons.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix,Numix-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
