name       : numix-icon-theme
version    : 23.01.12
release    : 23
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/refs/tags/23.01.12.tar.gz : b15f63a607fe405cb7e863277224cbcb85f025d17e28c56b9425636317f80c84
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly coloured background for applications and simplistic devices, toolbars and status icons.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix,Numix-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
