name       : numix-icon-theme
version    : 17.04.05
release    : 13
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/17-04-05.tar.gz : f8ae3c08c23412fdfeb4b322d1b788940d1cddda0068aca78762fd579aaf2bd0
license    : GPL-3.0
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
