name        : numix-icon-theme
version     : 20150615
release     : 10
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme/numix-icon-theme_0.3+444~201506150202~ubuntu15.04.1.tar.xz : f7c19e6ceb3707e113e48fb6cdd740319db4dbc6860557f509f9f43d2956f787
license     : GPL-3.0+
summary     : The Numix Icon Theme
description : |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
