name       : numix-icon-theme
version    : 17.12.25
release    : 14
source     :
    - https://github.com/numixproject/numix-icon-theme/archive/17-12-25.tar.gz : 768b9bcd77ecf51765683ecaf9aa77c220a92af3e5b19f89830ac0b5f7ffef49
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Numix Icon Theme
description: |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
